[package]
name = "assemblash-cli"
description = "Assemblash command-line interface"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "assemblash"
path = "src/main.rs"

[dependencies]
assemblash-core.workspace = true
assemblash-renderer.workspace = true

[lints]
workspace = true
