#!/usr/bin/env python3
"""Generate the explicit embedded asset list and the login dependency list."""

import argparse
import json
import posixpath
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIST = ROOT / "ui" / "dist"
OUTPUT = ROOT / "crates" / "assemblash-server" / "src" / "ui_assets.rs"
TYPES = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".json": "application/json; charset=utf-8",
    ".svg": "image/svg+xml",
    ".woff2": "font/woff2",
    ".txt": "text/plain; charset=utf-8",
}


def dependencies(name):
    path = DIST / name
    if path.suffix not in {".html", ".css", ".js"}:
        return set()
    source = path.read_text(encoding="utf-8")
    if path.suffix == ".html":
        references = re.findall(r'(?:src|href)=["\']([^"\']+)["\']', source)
    elif path.suffix == ".css":
        references = re.findall(r'url\(["\']?([^\)"\']+)', source)
        references += re.findall(r'@import\s+["\']([^"\']+)', source)
    else:
        references = re.findall(
            r'(?:\bfrom\s*|\bimport\s*(?:\(\s*)?)["\'](\./[^"\']+)["\']',
            source,
        )
    result = set()
    for reference in references:
        if reference.startswith(("data:", "http:", "https:", "#")):
            continue
        relative = reference.split("?", 1)[0].split("#", 1)[0]
        if relative.startswith("/"):
            resolved = posixpath.normpath(relative.lstrip("/"))
        else:
            resolved = posixpath.normpath(posixpath.join(posixpath.dirname(name), relative))
        if resolved == ".." or resolved.startswith("../") or not (DIST / resolved).is_file():
            raise ValueError(f"Missing local asset: {name} -> {reference}")
        result.add(resolved)
    return result


def generate():
    names = sorted(path.relative_to(DIST).as_posix() for path in DIST.rglob("*") if path.is_file())
    if not names:
        raise ValueError("Build the interface before generating its embedded assets")
    login = set()
    pending = ["login.html"]
    while pending:
        name = pending.pop()
        if name in login:
            continue
        login.add(name)
        pending.extend(dependencies(name) - login)
    lines = [
        "// Generated by scripts/ui_assets.py. Do not edit.",
        "// The login list contains only its local dependency graph.",
        "#[rustfmt::skip]",
        "pub(crate) fn is_login_asset(path: &str) -> bool {",
        "    matches!(path,",
    ]
    lines.append("        " + " | ".join(json.dumps("/" + name) for name in sorted(login)))
    lines.extend(["    )", "}", "", "#[rustfmt::skip]", "const ASSETS: &[Asset] = &["])
    for name in names:
        content_type = TYPES.get(Path(name).suffix)
        if content_type is None:
            raise ValueError(f"Unsupported browser asset: {name}")
        lines.extend([
            "    Asset {",
            f"        name: {json.dumps(name)},",
            f"        content_type: {json.dumps(content_type)},",
            f'        body: include_bytes!("../../../ui/dist/{name}"),',
            "    },",
        ])
    lines.extend([
        "];", "", "#[cfg(test)]", "#[test]", "#[rustfmt::skip]",
        "fn the_login_allowlist_contains_only_embedded_files() {",
        "    for path in [",
        *(f"        {json.dumps('/' + name)}," for name in sorted(login)),
        "    ] {",
        "        assert!(ASSETS.iter().any(|asset| asset.name == &path[1..]));",
        "        assert!(is_login_asset(path));",
        "    }",
        '    assert!(!is_login_asset("/main.js"));',
        '    assert!(!is_login_asset("/api/projects"));',
        "}", "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generate()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit("Embedded assets are stale. Run python scripts/ui_assets.py.")
    else:
        OUTPUT.write_text(expected, encoding="utf-8", newline="\n")
    print("Embedded assets and login dependencies match the interface build.")


if __name__ == "__main__":
    main()
