// Generated by scripts/ui_assets.py. Do not edit.
// The login list contains only its local dependency graph.
#[rustfmt::skip]
pub(crate) fn is_login_asset(path: &str) -> bool {
    matches!(path,
        "/chunk-Title.js" | "/chunk-mantine-root.js" | "/i18n.js" | "/login.html" | "/login.js" | "/ui.css"
    )
}

#[rustfmt::skip]
const ASSETS: &[Asset] = &[
    Asset {
        name: "Phosphor.woff2",
        content_type: "font/woff2",
        body: include_bytes!("../../../ui/dist/Phosphor.woff2"),
    },
    Asset {
        name: "catalogue-specimens/inter.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/inter.svg"),
    },
    Asset {
        name: "catalogue-specimens/jetbrains-mono.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/jetbrains-mono.svg"),
    },
    Asset {
        name: "catalogue-specimens/licenses/inter-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/inter-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/jetbrains-mono-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/jetbrains-mono-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/lora-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/lora-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/montserrat-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/montserrat-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/open-sans-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/open-sans-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/playfair-display-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/playfair-display-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/licenses/roboto-OFL.txt",
        content_type: "text/plain; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/licenses/roboto-OFL.txt"),
    },
    Asset {
        name: "catalogue-specimens/lora.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/lora.svg"),
    },
    Asset {
        name: "catalogue-specimens/manifest.json",
        content_type: "application/json; charset=utf-8",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/manifest.json"),
    },
    Asset {
        name: "catalogue-specimens/montserrat.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/montserrat.svg"),
    },
    Asset {
        name: "catalogue-specimens/open-sans.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/open-sans.svg"),
    },
    Asset {
        name: "catalogue-specimens/playfair-display.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/playfair-display.svg"),
    },
    Asset {
        name: "catalogue-specimens/roboto.svg",
        content_type: "image/svg+xml",
        body: include_bytes!("../../../ui/dist/catalogue-specimens/roboto.svg"),
    },
    Asset {
        name: "chunk-Title.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/chunk-Title.js"),
    },
    Asset {
        name: "chunk-app.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/chunk-app.js"),
    },
    Asset {
        name: "chunk-main.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/chunk-main.js"),
    },
    Asset {
        name: "chunk-mantine-root.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/chunk-mantine-root.js"),
    },
    Asset {
        name: "i18n.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/i18n.js"),
    },
    Asset {
        name: "index.html",
        content_type: "text/html; charset=utf-8",
        body: include_bytes!("../../../ui/dist/index.html"),
    },
    Asset {
        name: "login.html",
        content_type: "text/html; charset=utf-8",
        body: include_bytes!("../../../ui/dist/login.html"),
    },
    Asset {
        name: "login.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/login.js"),
    },
    Asset {
        name: "main.js",
        content_type: "text/javascript; charset=utf-8",
        body: include_bytes!("../../../ui/dist/main.js"),
    },
    Asset {
        name: "phosphor.css",
        content_type: "text/css; charset=utf-8",
        body: include_bytes!("../../../ui/dist/phosphor.css"),
    },
    Asset {
        name: "studio.css",
        content_type: "text/css; charset=utf-8",
        body: include_bytes!("../../../ui/dist/studio.css"),
    },
    Asset {
        name: "ui.css",
        content_type: "text/css; charset=utf-8",
        body: include_bytes!("../../../ui/dist/ui.css"),
    },
];

#[cfg(test)]
#[test]
#[rustfmt::skip]
fn the_login_allowlist_contains_only_embedded_files() {
    for path in [
        "/chunk-Title.js",
        "/chunk-mantine-root.js",
        "/i18n.js",
        "/login.html",
        "/login.js",
        "/ui.css",
    ] {
        assert!(ASSETS.iter().any(|asset| asset.name == &path[1..]));
        assert!(is_login_asset(path));
    }
    assert!(!is_login_asset("/main.js"));
    assert!(!is_login_asset("/api/projects"));
}
